### ISSUE TITLE
Yarn Pnp: @n1ru4l/graphql-live-query tried to access tslib

### ISSUE THREAD

**Issue by simPod** [n1ru4l/graphql-live-query#967]
Getting this error:

> Error: @n1ru4l/graphql-live-query tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

when using yarn (v3.2) Pnp.

with

```
"@n1ru4l/graphql-live-query@npm:^0.10.0":
  version: 0.10.0
  resolution: "@n1ru4l/graphql-live-query@npm:0.10.0"
  peerDependencies:
    graphql: ^15.4.0 || ^16.0.0
  checksum: c50414f56f9aa7bc60cf73847498fe94dc220f069343a4b8a3feb4f94f588649ab5e9c713e45a7d9c930c0d4337d861fbdc971350b90147eec9215503bb8aeaa
  languageName: node
  linkType: hard
```
